{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}

package:
  name: test_versioneer
  version: {{GIT_VERSION}}
source:
  git_url: ../
build:
  number: 0
requirements:
  build:

  run:
